### ISSUE TITLE
German localization is missing

### ISSUE THREAD

**Issue by jliebich** [wallabag/wallabagger#122]
As far as I see from the source code, only 3 languages are avialable: englisch (en), french (fr) and russian (ru)

I miss (my native language) german.

Here is my german translation of messages.json for the directory wallabager/_locales/de

[messages.json.txt](https://github.com/wallabag/wallabagger/files/1598024/messages.json.txt)

**Comment by Strubbl** [comment]
Thanks @jliebich for providing the translation. I added it in the PR #123 
Also, i made some minor improvements. Can you please review them? The changes i made to your translation are summarized in a separate commit: https://github.com/wallabag/wallabagger/pull/123/commits/03d1b38c576b354b7246b2d58124946ec3e6e76e

I know, that wallabag is a proper name. According to @nicosomb it is his wish to always write it in lowercase letters - maybe except the beginning of a sentence. That's why i changed the W in wallabag to a small w. I know this is not yet consistent in all translations, but let's start it here to become more consistent.

**Comment by jliebich** [comment]
Thanks for your quick reaction.
Checked your changes - everything okay!

**Comment by Simounet** [comment]
That's great! Thank you for your time.
