### ISSUE TITLE
Switch icon to white when browser is in dark mode

### ISSUE THREAD

**Issue by BuzzKnightbeer** [wallabag/wallabagger#156]
When Firefox is set to dark mode / theme the icon stays black and doesn't really fit in. It would be great if it could switch do a white icon when the current page is not yet saved.

![wallabagger_darkmode](https://user-images.githubusercontent.com/45749699/49713325-2ebf3b80-fc83-11e8-9c14-4af757f13cf6.JPG)

**Comment by Rurik19** [comment]
Is it possible to detect if the theme is dark? The better solution might be an outlined icon. like in the edge version of wallabagger

**Comment by BuzzKnightbeer** [comment]
> 
> 
> Is it possible to detect if the theme is dark? The better solution might be an outlined icon. like in the edge version of wallabagger

I'm no developer, so I don't know if this is helpful, but I found this:

[How to correctly design color icon to be visible accross themes](https://discourse.mozilla.org/t/how-to-correctly-design-color-icon-to-be-visible-across-themes/27713)
[How to detect Firefox Theme](https://stackoverflow.com/questions/37366781/how-to-detect-firefox-theme)

**Comment by prcmt** [comment]
Firefox supports specifying [dark and light versions of the browser action icon](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#theme_icons) in the manifest. This is not supported elsewhere AFAIK but would be worth doing.

```json
"browser_action": {
  "default_title": "Wallabagger",
  "default_icon": "img/wallabagger-dark.svg",
  "theme_icons": [{
    "dark": "img/wallabagger-dark.svg",
    "light": "img/wallabagger-light.svg",
    "size": 32
  }],
  "default_popup": "popup.html"
}
```

Unfortunately, I don't know that we can detect whether a theme is light or dark - which you'd need to do [here](https://github.com/wallabag/wallabagger/blob/61a67b1c871c3a5e3f29a16cb46b51d57a39ab6f/wallabagger/js/background.js#L330) otherwise the icon will revert back to the default colour after it's clicked.

**Comment by prcmt** [comment]
Actually, it looks like passing `null` to [`setIcon`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon) produces the desired behaviour of setting the icon to the theme appropriate default.

I've updated #182 to include light and dark icon variants. :)
