### ISSUE TITLE
Rename wallabagger to wallabag?

### ISSUE THREAD

**Issue by jlnostr** [wallabag/wallabagger#35]
Is there a specific reason, why the now official plugin for wallabag is called "wallabagger"? All the other apps are called wallabag, so why is this plugin different?

ping @wallabag/core

**Comment by Simounet** [comment]
@Rurik19 will tell that but I guess this was not an official project at first but now, it makes sense to rename it.

**Comment by tcitworld** [comment]
I'm fine with wallabagger, it's nice.

**Comment by Rurik19** [comment]
Hi all! 

I am against renaming because:

- I'm used to this name
- ~900 users used to this name
- Suffix -er to all english-speaking means "tool to work with.." - it is good for recognition
- When all apps called the same - it is boring (meanwhile - previous official plugin was: **wallabag-it**)

And I am against changing icon! :)
