### ISSUE TITLE
Auto add single tag & Retrieve content from the browser by default when saving page

### ISSUE THREAD

**Issue by blogdemoi** [wallabag/wallabagger#350]
Hi,

Could you explain what are the following two options? : 

-Auto add single tag
-Retrieve content from the browser by default when saving page

Thank you.

**Comment by Simounet** [comment]
Hi @blogdemoi ,
The new option page layout with section is the first part of categorizing these options. They need to be more obvious, your issue is a new example.
-Auto add single tag
-> When you are typing a tag in the popup on adding an entry with the wallabagger icon, if there is only one existing matching tag on your wallabag account, it will be added automatically, without any other validation. Hard to explain.
-Retrieve content from the browser by default when saving page
-> For websites with paywall, if you are logged in through your browser, wallabagger will send the content you are seeing to the server instead of the server trying to get the content with the paywall.
Let me know if it's not clear. We need to update the text of these options.

**Comment by blogdemoi** [comment]
It is very clear now! Thank you.
