### ISSUE TITLE
Please support Tor Browser

### ISSUE THREAD

**Issue by 1xPdd** [wallabag/wallabagger#91]
On the Tor Browser 7.0.1 on Debian Stretch, I'm unable to check my Wallabag URL... Pressing the button to do so appears to do nothing. It would be incredibly useful to use Wallabager through Tor. Please consider simplifying the settings or allowing a fallback (e.g., completely manual entry without any checking'). Thanks!

**Comment by Rurik19** [comment]
Hi! If it cannot check URL it very possible that it won't work at all...

**Comment by Rurik19** [comment]
There is NO-SCRIPT extension who blocks wallabagger. Either disable it or setup white list for your wallabag installation.

**Comment by 1xPdd** [comment]
Disabling NoScript doesn't seem to have an effect. Thanks, though.

**Comment by Simounet** [comment]
If you're concerned about privacy, I think this is not a good idea to use wallabagger. [Tor doesn't recommend use of addons with it's browser because of finger printing](https://www.torproject.org/docs/faq.html.en#TBBOtherExtensions). You can use the bookmarklet instead. I tried it and it worked.
I can investigate any further about wallabagger if you really want to.
